python experiments.py --model=simple-cnn \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label1 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label2 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label3 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.3\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.1\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=svhn \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label1 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=svhn \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label2 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=svhn \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label3 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=svhn \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=svhn \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.3\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=svhn \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.1\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2
	
python experiments.py --model=simple-cnn \
	--dataset=fmnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label1 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=fmnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label2 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=fmnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label3 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=fmnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=fmnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.3\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=fmnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.1\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=mnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label1 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=mnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label2 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=mnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label3 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=mnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=mnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.3\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=simple-cnn \
	--dataset=mnist \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.1\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=vgg-9 \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label1 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=vgg-9 \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label2 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=vgg-9 \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-#label3 \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=vgg-9 \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.5\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=vgg-9 \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.3\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2

python experiments.py --model=vgg-9 \
	--dataset=cifar10 \
	--alg=vote \
	--lr=0.001 \
	--batch-size=64 \
	--epochs=200 \
	--n_parties=10 \
	--rho=0.9 \
	--comm_round=100 \
	--partition=noniid-labeldir \
	--beta=0.1\
	--device='cuda:7'\
	--datadir='./data/' \
	--logdir='./logs/' \
	--noise=0\
	--init_seed=2
